#pragma once
#include <iostream>
#include <fstream>
#include <filesystem>
#include <Windows.h>
#include <string>     
#include <chrono>      
#include <cstddef>
#include <conio.h>
#include <cstdlib>
#include <strsafe.h>
#include <stdlib.h>
#include <stdint.h>
#include <ostream>
#include <regex>
#include <thread>
#include <random>
#include <fstream>
#include <sstream>
#include <ctime>
#include <tchar.h>
#include <string_view>
#include <time.h>
#include <memory>
#include <TlHelp32.h>
#include <cstdint>
#include <vector>